clear
clc

% import input file from working directory
fileID = fopen('input101.txt');
import_data_cell = textscan(fileID, '%f64');
import_data_vec  = import_data_cell{1,1};
fclose(fileID);

% testbench file generated by simulation of fpga
tb_fileID = fopen('output101_functional_sim.txt');
import_data_tb_cell = textscan(tb_fileID, '%f64');
import_data_vec_tb  = import_data_tb_cell{1,1};
fclose(tb_fileID);

% create time series
t = linspace(0, 10, 3000)';
input_tseries = timeseries(import_data_vec   , t);
tb_tseries    = timeseries(import_data_vec_tb, t);

